### ISSUE TITLE
Let python-varname use the pypi name varname

### ISSUE THREAD

**Issue by alexmojaki** [HanyuuLu/storge#21]
https://github.com/pwwang/python-varname is a project I have contributed to. It provides the same functionality as `varName`, although the function there is called `nameof` (like in C#). It has many advantages:

- Works without access to source code, e.g. in the Python shell/REPL.
- Works if the function is renamed to something other than `nameof`.
- Works if the call is spread across many lines.
- Works if the function is called many times on one line.
- Can accept multiple arguments and return a tuple of names.
- Can accept an attribute as an argument, e.g. `nameof(foo.bar) == 'bar'`.

Would you please consider deprecating this project and handing the pypi package name over to @pwwang? This would let users write `pip install varname` (which can easily happen by mistake already) instead of `pip install python-varname` which is redundant and counter-intuitive.

**Comment by HanyuuLu** [comment]
> https://github.com/pwwang/python-varname is a project I have contributed to. It provides the same functionality as `varName`, although the function there is called `nameof` (like in C#). It has many advantages:
> 
>     * Works without access to source code, e.g. in the Python shell/REPL.
> 
>     * Works if the function is renamed to something other than `nameof`.
> 
>     * Works if the call is spread across many lines.
> 
>     * Works if the function is called many times on one line.
> 
>     * Can accept multiple arguments and return a tuple of names.
> 
>     * Can accept an attribute as an argument, e.g. `nameof(foo.bar) == 'bar'`.
> 
> 
> Would you please consider deprecating this project and handing the pypi package name over to @pwwang? This would let users write `pip install varname` (which can easily happen by mistake already) instead of `pip install python-varname` which is redundant and counter-intuitive.

I have delete `varName` and you can use it.

**Comment by alexmojaki** [comment]
Awesome, thanks! @pwwang, can you take it from here?

**Comment by pwwang** [comment]
Thank you both! Very much appreciated!

**Comment by pwwang** [comment]
@HanyuuLu Just want to let you know that I have added a special-thanks mention in [python-varname][1]'s README file.

[1]: https://github.com/pwwang/python-varname

**Comment by HanyuuLu** [comment]
> @HanyuuLu Just want to let you know that I have added a special-thanks mention in [python-varname](https://github.com/pwwang/python-varname)'s README file.

got it.
